let arra = [""];

// user email
const userEmail = document.getElementById("email").value;
// user password
const userPass = document.getElementById("pass").value;
function btn(){

  console.log(userEmail);
}
// user email and password submint
// const userSubmint = document.getElementById("sub");
// arra.push(userEmail);

// let a = (items) => {
//   items = userSubmint.addEventListener(
//     "click",
//     console.log(arra, "pprint you name")
//   );
// };
